"""init runs

Revision ID: 8e3e7aa92bc6
Revises: 88e85c6ea4b2
Create Date: 2025-11-07 19:56:04.446615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3e7aa92bc6'
down_revision: Union[str, Sequence[str], None] = '88e85c6ea4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SIMULATED', 'APPROVED', 'EXECUTING', 'DEPLOYED', 'ROLLED_BACK', 'BLOCKED_DRIFT', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    # ### end Alembic commands ###
