"""runs simulation fields

Revision ID: c5901cba78f7
Revises: 8e3e7aa92bc6
Create Date: 2025-11-07 20:00:07.037222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5901cba78f7'
down_revision: Union[str, Sequence[str], None] = '8e3e7aa92bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_marker', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tool_plan', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('changelist', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('slack_preview', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('approved_by')
        batch_op.drop_column('slack_preview')
        batch_op.drop_column('changelist')
        batch_op.drop_column('tool_plan')
        batch_op.drop_column('version_marker')
    # ### end Alembic commands ###
